baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "akelacena"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "chat"
name = "Chat"
weight = "4"
[[menu.main]]
URL = "commands"
name = "Commands"
weight = "5"
[[menu.main]]
URL = "setup"
name = "Setup"
weight = "6"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = "7"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "akelacena"
description = "Official Site"
[params.banner]
heading = "Official Site"
image = "images/base_final.png"
[params.blog]
heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[params.footer]
address = "https://www.twitch.tv/akelacena"
content = "I love gaming, I love streaming, I love my community 🤙 I'm Portuguese, I'm a father 👨‍👧 and 40 years old. PC is my platform (YES I play with a 🖱). FPS is my genre, be it Battle Royale, Multiplayer, Cooperative or even Story mode. 💣"
copyright = "© akelacena 2021"
hours = "Everyday, Always"
title = "About Me"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "https://www.facebook.com/akelacena.twitch"
instagram = "https://www.instagram.com/akelacena/"
linkedin = ""
twitter = "https://twitter.com/akelacena"
yelp = ""
[taxonomies]
author = "akelacena"
category = "categories"
tag = "tags"
